# These are supported funding model platforms

github: [juliencrn]
# patreon: # Replace with a single Patreon username
# open_collective: #usehooks-ts # Replace with a single Open Collective username
# ko_fi: # Replace with a single Ko-fi username
# tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
# community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
# liberapay: # Replace with a single Liberapay username
# issuehunt: # Replace with a single IssueHunt username
# otechie: # Replace with a single Otechie username
# lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: [
  "https://juliencaron.com/donate",
  "https://www.paypal.com/paypalme/juliencrn",
  "https://buy.stripe.com/fZefZY8Bv32cg9O3cc",
  "https://www.buymeacoffee.com/juliencrn"
]
