export * from './useBoolean'
export * from './useClickAnyWhere'
export * from './useCopyToClipboard'
export * from './useCountdown'
export * from './useCounter'
export * from './useDarkMode'
export * from './useDebounce'
export * from './useEffectOnce'
export * from './useElementSize'
export * from './useEventListener'
export * from './useFetch'
export * from './useHover'
export * from './useImageOnLoad'
export * from './useIntersectionObserver'
export * from './useInterval'
export * from './useIsClient'
export * from './useIsFirstRender'
export * from './useIsMounted'
export * from './useIsomorphicLayoutEffect'
export * from './useLocalStorage'
export * from './useLockedBody'
export * from './useMap'
export * from './useMediaQuery'
export * from './useOnClickOutside'
export * from './useReadLocalStorage'
export * from './useScreen'
export * from './useScript'
export * from './useSsr'
export * from './useStep'
export * from './useTernaryDarkMode'
export * from './useTimeout'
export * from './useUpdateEffect'
export * from './useWindowSize'

export function isEsm() {
  console.log('Hello, World! from isEsm function')
  // The exports variable will be undefined in an ES module, but not in CommonJS
  // So, we can use it to discriminate between CommonJS and ES modules
  return typeof exports === 'undefined'
}
